export const clientConfig = {
  clientId: "pwc",
  clientName: "PwC",
  productName: "PwC Partner Narrative Kits",
  productLine: "Partner Narrative Studio",
  productFraming:
    "Turn approved PwC narratives into partner-ready posts, comments, emails and talking points.",
  pilotTopic: "Human Scale AI",
  language: "English",
  marketScope: ["Global", "UK", "Financial Services", "TMT"],
  lastSeededAt: "2026-06-19",
};

export const messageSpine = {
  coreTruth:
    "Fluent content is abundant. Distinct expert judgement is scarce.",
  provocation:
    "AI is making sameness cheaper; distinct expert judgement is becoming scarce.",
  systemClaim:
    "PwC can use AI to coordinate the system behind its people while protecting their voices.",
  measure:
    "Measure mental availability through culture: what leaders recognise, use and pass on.",
  operatingModel: [
    "PwC point of view",
    "Approved content base",
    "Partners and experts",
    "Client and prospect networks",
    "Wider business conversation",
    "Cultural authority and mental availability",
  ],
  claimsToAvoid: [
    "AI will replace expert judgement.",
    "Generic AI output is enough to build market authority.",
    "Every asset should become a social post.",
    "Cultural availability can be inferred from vanity engagement metrics alone.",
    "Public profile scraping is an approved source of partner perspective.",
  ],
  priorityMoments: [
    "Setting strategy",
    "Exploring opportunities",
    "Seeking help",
    "Delivery confidence",
    "Event follow-up",
    "Market trigger",
  ],
  sectorCuts: [
    {
      sector: "Financial Services",
      angle:
        "AI opportunity is strongest when governance, risk, workforce redesign and client outcomes move together.",
    },
    {
      sector: "TMT",
      angle:
        "AI is already core to the sector's operating model; the scarce layer is credible human judgement about where value moves next.",
    },
    {
      sector: "UK market",
      angle:
        "Translate global AI proof into practical UK executive questions on productivity, resilience, skills and trust.",
    },
  ],
  roleCuts: [
    {
      role: "CEO",
      angle: "Turn AI from scattered pilots into business model reinvention and growth bets.",
    },
    {
      role: "CFO",
      angle: "Separate AI cost activity from measured value creation, reuse and scale discipline.",
    },
    {
      role: "CIO / CTO",
      angle: "Build reusable AI foundations, data quality and guardrails that let teams move faster safely.",
    },
    {
      role: "CHRO",
      angle: "Redesign work, skills and early career pathways around human-intensive capabilities.",
    },
    {
      role: "CRO / Risk leader",
      angle: "Make AI governance operational enough to support trust, compliance and adoption.",
    },
    {
      role: "CMO",
      angle: "Build cultural availability by equipping experts with useful proof, not more generic output.",
    },
  ],
  partnerInterpretationPrompts: [
    "Where are clients still treating AI as efficiency rather than reinvention?",
    "Which proof point would make this feel real in your sector?",
    "What judgement would you add that a generic AI summary would miss?",
    "Which client moment does this asset belong in?",
    "What claim should we avoid because it overstates the evidence?",
  ],
};

export const taxonomy = {
  topics: [
    "Human Scale AI",
    "Responsible AI",
    "AI assurance and trust",
    "AI regulation and resilience",
    "AI transformation",
    "AI infrastructure and platforms",
    "Data and trust",
    "Digital transformation",
    "Workforce and AI",
    "Risk and governance",
    "Financial Services AI",
    "TMT AI",
  ],
  sectors: ["Financial Services", "TMT", "Healthcare", "Energy", "Consumer Markets", "UK market", "Global markets"],
  roles: ["CEO", "CFO", "CIO / CTO", "CHRO", "Risk leader", "Transformation leader", "CMO"],
  moments: messageSpine.priorityMoments,
  contentRoles: [
    "Core POV",
    "Proof point",
    "Sector cut",
    "Role cut",
    "Partner prompt",
    "Sales note",
    "Event follow-up",
    "Search / AI answer brief",
    "Background",
  ],
  funnelStages: [
    "Thought leadership",
    "Education",
    "Proof",
    "Consideration",
    "Sales enablement",
    "Executive POV",
    "Background",
  ],
  metadataStatuses: ["Human approved", "Human edited", "AI suggested", "Needs review"],
  activationLabels: [
    "Core spine asset",
    "Strong proof point",
    "Partner prompt source",
    "Sector cut",
    "Conversation starter",
    "Sales follow-up",
    "Needs sharper POV",
    "Needs stronger proof",
    "Background only",
  ],
  partnerPromptTypes: [
    "LinkedIn post starter",
    "Comment starter",
    "Short video prompt",
    "Client email starter",
    "Event follow-up note",
    "Sales talking point",
    "Q&A prep",
  ],
  partnerStyles: ["Field note", "Boardroom", "Reflective", "Practical", "Direct"],
};

const commonClaimsToAvoid = [
  "Do not imply guaranteed AI ROI.",
  "Do not present AI as a substitute for professional judgement.",
  "Do not use client-specific claims without approval.",
];

export const contentAssets = [
  {
    id: "pwc-ai-services",
    title: "Artificial intelligence services",
    url: "https://www.pwc.com/gx/en/services/ai.html",
    canonical_url: "https://www.pwc.com/gx/en/services/ai.html",
    source_type: "PwC services page",
    platform: "pwc.com",
    format: "Service page",
    language: "English",
    region: "Global",
    published_date: null,
    last_seen_date: "2026-06-19",
    last_crawled_date: "2026-06-19",
    raw_text:
      "PwC frames AI success around the right strategy, rich insights, bold execution and a future of work that is dynamic, resilient and human-led by design.",
    summary:
      "Primary PwC AI proposition page: human-led, tech-powered AI transformation with strategy, data, governance, workforce and measurable outcomes.",
    primary_topic: "Human Scale AI",
    secondary_topics: ["AI transformation", "Responsible AI", "Data and trust"],
    audience: ["CEO", "CIO / CTO", "CHRO", "CMO"],
    business_area: "Artificial intelligence",
    funnel_stage: "Thought leadership",
    key_claims: [
      "Real AI success comes from strategy, insights and execution, not technology alone.",
      "Agentic AI requires redesigning value chains, processes, workflows, roles and skills.",
      "PwC positions the future of work as dynamic, resilient and human-led by design.",
    ],
    proof_points: [
      "PwC states that agentic AI requires redesigning value chains, processes and workflows around hybrid AI-human teams.",
      "PwC describes responsible AI as including security, ethics, compliance, controls and governance across the value chain.",
      "PwC's AI services include AI-readiness assessments, simulations, organisational change, AI training and governance models.",
    ],
    suggested_use:
      "Use as the core spine asset for explaining Human Scale AI as business reinvention led by expert judgement.",
    suggested_sales_enablement_use:
      "Open executive conversations on where AI needs strategy, governance, workforce change and measurable outcomes.",
    related_asset_ids: ["pwc-ai-performance", "pwc-ai-jobs-global", "pwc-ceo-survey-ai"],
    ai_confidence_score: 0.94,
    metadata_status: "Human approved",
    content_usefulness: "Core spine asset",
    url_status: "Accessible",
    message_role: "Core POV",
    message_spine_alignment: 5,
    core_truth_supported: true,
    provocation_supported: true,
    claims_to_avoid: commonClaimsToAvoid,
    sector_cuts: ["Financial Services", "TMT", "UK market", "Global markets"],
    role_cuts: ["CEO", "CIO / CTO", "CHRO", "CMO"],
    moments_that_matter: ["I am setting my strategy", "I want PwC's help"],
    partner_prompt_types: ["LinkedIn post starter", "Short video prompt", "Q&A prep"],
    cultural_availability_score: 5,
    partner_readiness_score: 5,
    proof_strength_score: 4,
    moment_readiness_score: 5,
    activation_quality_total: 24,
    activation_labels: ["Core spine asset", "Partner prompt source", "Conversation starter"],
    recommended_partner_use:
      "Use as a first-principles opener before moving into sector proof or a client-specific moment.",
    why_it_matters:
      "It makes the human layer explicit: approved proof supports the structure, but partner judgement carries the point of view.",
  },
  {
    id: "pwc-ai-jobs-global",
    title: "2026 Global AI Jobs Barometer",
    url: "https://www.pwc.com/gx/en/services/ai/ai-jobs-barometer.html",
    canonical_url: "https://www.pwc.com/gx/en/services/ai/ai-jobs-barometer.html",
    source_type: "PwC research report",
    platform: "pwc.com",
    format: "Research report",
    language: "English",
    region: "Global",
    published_date: "2026-06-16",
    last_seen_date: "2026-06-19",
    last_crawled_date: "2026-06-19",
    raw_text:
      "PwC's 2026 AI Jobs Barometer examines more than one billion job ads across six continents and links AI exposure to productivity, skills change, wages and redesigned entry pathways.",
    summary:
      "A proof-rich workforce report showing AI is increasing the premium on human-intensive skills and changing how roles develop.",
    primary_topic: "Workforce and AI",
    secondary_topics: ["Human Scale AI", "AI transformation", "Risk and governance"],
    audience: ["CEO", "CHRO", "CIO / CTO"],
    business_area: "Workforce",
    funnel_stage: "Proof",
    key_claims: [
      "AI is accelerating skills change and redesigning entry-level work.",
      "Professionalised jobs are thriving where AI leaves more expert tasks for people.",
      "Businesses should invest in human-intensive skills alongside AI skills.",
    ],
    proof_points: [
      "The report examines over one billion job ads from six continents.",
      "Productivity growth is 40% higher at the most AI-exposed companies than the least AI-exposed companies.",
      "Professionalised jobs are growing twice as fast as democratised jobs with 42% higher wage growth since 2021.",
      "The most AI-exposed junior roles are seven times more likely to demand traditionally senior skills like leadership.",
    ],
    suggested_use:
      "Use as proof that the Human Scale argument is not sentimental; AI is raising the value of human judgement, leadership and creativity.",
    suggested_sales_enablement_use:
      "Equip CHRO and CEO conversations on skills, early career pathways and workforce redesign.",
    related_asset_ids: ["pwc-fs-ai-jobs", "pwc-tmt-ai-jobs", "pwc-ai-services"],
    ai_confidence_score: 0.96,
    metadata_status: "Human approved",
    content_usefulness: "Strong proof point",
    url_status: "Accessible",
    message_role: "Proof point",
    message_spine_alignment: 5,
    core_truth_supported: true,
    provocation_supported: true,
    claims_to_avoid: commonClaimsToAvoid,
    sector_cuts: ["Financial Services", "TMT", "Global markets"],
    role_cuts: ["CEO", "CHRO", "CIO / CTO"],
    moments_that_matter: ["I am setting my strategy", "I am exploring opportunities"],
    partner_prompt_types: ["LinkedIn post starter", "Comment starter", "Client email starter"],
    cultural_availability_score: 5,
    partner_readiness_score: 5,
    proof_strength_score: 5,
    moment_readiness_score: 4,
    activation_quality_total: 24,
    activation_labels: ["Strong proof point", "Partner prompt source", "Conversation starter"],
    recommended_partner_use:
      "Use one workforce proof point to make the Human Scale AI argument concrete for leaders.",
    why_it_matters:
      "It gives partners a memorable stat-backed bridge from AI adoption to human expertise.",
  },
  {
    id: "pwc-ceo-survey-ai",
    title: "PwC's 29th Global CEO Survey",
    url: "https://www.pwc.com/gx/en/issues/c-suite-insights/ceo-survey.html",
    canonical_url: "https://www.pwc.com/gx/en/issues/c-suite-insights/ceo-survey.html",
    source_type: "PwC flagship survey",
    platform: "pwc.com",
    format: "Survey report",
    language: "English",
    region: "Global",
    published_date: "2026-01-19",
    last_seen_date: "2026-06-19",
    last_crawled_date: "2026-06-19",
    raw_text:
      "PwC's CEO Survey positions leaders as balancing near-term threats with long-term reinvention, with AI investment continuing even when immediate returns are elusive.",
    summary:
      "A senior executive proof base for linking AI, uncertainty, reinvention and growth opportunities.",
    primary_topic: "AI transformation",
    secondary_topics: ["Human Scale AI", "Digital transformation", "Risk and governance"],
    audience: ["CEO", "CFO", "CMO"],
    business_area: "C-suite insights",
    funnel_stage: "Executive POV",
    key_claims: [
      "CEOs are investing in AI while navigating uncertainty and searching for reinvention opportunities.",
      "Leaders moving fast on reinvention are outperforming peers.",
      "AI sits within a broader reconfiguration of industries and value pools.",
    ],
    proof_points: [
      "The 29th Global CEO Survey is based on responses from 4,454 chief executives across 95 countries and territories.",
      "30% of CEOs report increased revenue from AI in the last 12 months.",
      "42% of CEOs say their company has begun competing in new sectors over the past five years.",
    ],
    suggested_use:
      "Use as executive context for why Human Scale AI should be framed around reinvention, not content production.",
    suggested_sales_enablement_use:
      "Anchor CEO and CFO conversations on AI value, uncertainty and sector boundary shifts.",
    related_asset_ids: ["pwc-ai-performance", "pwc-ai-services"],
    ai_confidence_score: 0.95,
    metadata_status: "Human approved",
    content_usefulness: "Executive POV",
    url_status: "Accessible",
    message_role: "Role cut",
    message_spine_alignment: 4,
    core_truth_supported: true,
    provocation_supported: false,
    claims_to_avoid: commonClaimsToAvoid,
    sector_cuts: ["Financial Services", "TMT", "Global markets"],
    role_cuts: ["CEO", "CFO", "CMO"],
    moments_that_matter: ["I am setting my strategy", "I am exploring opportunities"],
    partner_prompt_types: ["LinkedIn post starter", "Client email starter", "Sales talking point"],
    cultural_availability_score: 5,
    partner_readiness_score: 4,
    proof_strength_score: 5,
    moment_readiness_score: 5,
    activation_quality_total: 24,
    activation_labels: ["Strong proof point", "Sales follow-up", "Conversation starter"],
    recommended_partner_use:
      "Use as an executive opener after a market event, board discussion or strategy reset.",
    why_it_matters:
      "It connects AI to the board-level agenda where preference and trust are formed.",
  },
  {
    id: "pwc-ai-performance",
    title: "Decoding ROI from AI",
    url: "https://www.pwc.com/gx/en/issues/technology/ai-performance.html",
    canonical_url: "https://www.pwc.com/gx/en/issues/technology/ai-performance.html",
    source_type: "PwC performance study",
    platform: "pwc.com",
    format: "Interactive insight",
    language: "English",
    region: "Global",
    published_date: "2026-06-01",
    last_seen_date: "2026-06-19",
    last_crawled_date: "2026-06-19",
    raw_text:
      "PwC's AI performance study argues that ROI is concentrated among AI leaders who focus AI on outcomes, build fit-for-purpose foundations and scale what works.",
    summary:
      "A proof-led study for moving the message from AI interest to value, reuse, governance and scaled performance.",
    primary_topic: "AI transformation",
    secondary_topics: ["AI infrastructure and platforms", "Data and trust", "Digital transformation"],
    audience: ["CEO", "CFO", "CIO / CTO"],
    business_area: "Technology",
    funnel_stage: "Proof",
    key_claims: [
      "AI leaders use AI for productivity, reinvention and growth.",
      "AI fitness depends on outcomes, foundations and scaling what works.",
      "The biggest returns come when AI changes value creation, not just task speed.",
    ],
    proof_points: [
      "PwC reports that 20% of companies are capturing 74% of all AI-driven value.",
      "The most AI-fit companies are getting a 7.2x AI-driven performance boost over peers.",
      "AI leaders are 2.6x as likely as others to say AI helps reinvent the business model.",
      "AI leaders are 2x as likely to embed AI end-to-end across the value chain.",
    ],
    suggested_use:
      "Use as the value proof for moving Human Scale AI from message to operating discipline.",
    suggested_sales_enablement_use:
      "Help CFOs and CIOs discuss portfolio discipline, reusable foundations and scaling decisions.",
    related_asset_ids: ["pwc-ai-services", "pwc-ceo-survey-ai"],
    ai_confidence_score: 0.96,
    metadata_status: "Human approved",
    content_usefulness: "Strong proof point",
    url_status: "Accessible",
    message_role: "Proof point",
    message_spine_alignment: 5,
    core_truth_supported: true,
    provocation_supported: true,
    claims_to_avoid: commonClaimsToAvoid,
    sector_cuts: ["Financial Services", "TMT", "Global markets"],
    role_cuts: ["CEO", "CFO", "CIO / CTO"],
    moments_that_matter: ["I am exploring opportunities", "I need you to deliver outcomes"],
    partner_prompt_types: ["Comment starter", "Client email starter", "Sales talking point", "Q&A prep"],
    cultural_availability_score: 5,
    partner_readiness_score: 5,
    proof_strength_score: 5,
    moment_readiness_score: 5,
    activation_quality_total: 25,
    activation_labels: ["Strong proof point", "Sales follow-up", "Core spine asset"],
    recommended_partner_use:
      "Use when a client is asking how to move from pilots to repeatable AI value.",
    why_it_matters:
      "It makes the operating-system claim tangible: the system behind experts determines whether AI value travels.",
  },
  {
    id: "pwc-fs-ai-jobs",
    title: "Financial Services and Private Equity AI Jobs Barometer sector report",
    url: "https://www.pwc.com/gx/en/issues/artificial-intelligence/job-barometer/2026/pwc-aijb-2026-financial-services-report.pdf",
    canonical_url:
      "https://www.pwc.com/gx/en/issues/artificial-intelligence/job-barometer/2026/pwc-aijb-2026-financial-services-report.pdf",
    source_type: "PwC sector report",
    platform: "pwc.com",
    format: "Sector PDF",
    language: "English",
    region: "Global",
    published_date: "2026-06-16",
    last_seen_date: "2026-06-19",
    last_crawled_date: "2026-06-19",
    raw_text:
      "PwC's Financial Services AI Jobs Barometer report shows AI hiring, exposure, productivity and wage premiums in financial services and private equity.",
    summary:
      "A Financial Services cut for partner-led activation around AI skills, productivity, exposure and governance.",
    primary_topic: "Financial Services AI",
    secondary_topics: ["Human Scale AI", "Workforce and AI", "Risk and governance"],
    audience: ["CEO", "CFO", "CHRO", "CRO / Risk leader"],
    business_area: "Financial Services",
    funnel_stage: "Proof",
    key_claims: [
      "Financial Services has a high exposure to AI tasks and growing demand for AI skills.",
      "AI hiring has accelerated in the sector even as broader labour demand remains slower.",
      "Most AI demand in Financial Services is applied AI, not specialist build roles alone.",
    ],
    proof_points: [
      "The share of AI job postings in Financial Services rose from 3.4% in 2024 to 5.4% in 2025.",
      "Financial Services AI roles surged by 77.4% in 2025 relative to 2024.",
      "Financial Services recorded a 53% AI wage premium in 2025.",
      "In 2025, AI user roles accounted for 88% of AI-related roles in Financial Services.",
    ],
    suggested_use:
      "Use as the pilot FS sector cut for AI transformation, skills and trusted adoption conversations.",
    suggested_sales_enablement_use:
      "Give FS partners a sector-native proof point for workforce, productivity and risk discussions.",
    related_asset_ids: ["pwc-ai-jobs-global", "pwc-ai-performance"],
    ai_confidence_score: 0.94,
    metadata_status: "Human approved",
    content_usefulness: "Sector cut",
    url_status: "Accessible",
    message_role: "Sector cut",
    message_spine_alignment: 4,
    core_truth_supported: true,
    provocation_supported: false,
    claims_to_avoid: commonClaimsToAvoid,
    sector_cuts: ["Financial Services"],
    role_cuts: ["CEO", "CFO", "CHRO", "CRO / Risk leader"],
    moments_that_matter: ["I am setting my strategy", "I need you to deliver outcomes"],
    partner_prompt_types: ["LinkedIn post starter", "Client email starter", "Event follow-up note"],
    cultural_availability_score: 4,
    partner_readiness_score: 5,
    proof_strength_score: 5,
    moment_readiness_score: 5,
    activation_quality_total: 24,
    activation_labels: ["Sector cut", "Strong proof point", "Sales follow-up"],
    recommended_partner_use:
      "Use for Financial Services partners who need one credible sector proof point before a meeting or event follow-up.",
    why_it_matters:
      "It turns the global Human Scale AI argument into a sector-native story about applied AI, risk and scarce skills.",
  },
  {
    id: "pwc-tmt-ai-jobs",
    title: "Technology, Media and Telecoms AI Jobs Barometer sector report",
    url: "https://www.pwc.com/gx/en/issues/artificial-intelligence/job-barometer/2026/pwc-aijb-2026-technology-media-and-telecoms-report.pdf",
    canonical_url:
      "https://www.pwc.com/gx/en/issues/artificial-intelligence/job-barometer/2026/pwc-aijb-2026-technology-media-and-telecoms-report.pdf",
    source_type: "PwC sector report",
    platform: "pwc.com",
    format: "Sector PDF",
    language: "English",
    region: "Global",
    published_date: "2026-06-16",
    last_seen_date: "2026-06-19",
    last_crawled_date: "2026-06-19",
    raw_text:
      "PwC's TMT AI Jobs Barometer report shows TMT leading AI hiring intensity and productivity growth while facing fast skills transformation.",
    summary:
      "A TMT sector cut for AI workforce, productivity, scarcity and platform-change conversations.",
    primary_topic: "TMT AI",
    secondary_topics: ["Human Scale AI", "AI infrastructure and platforms", "Workforce and AI"],
    audience: ["CEO", "CIO / CTO", "CHRO", "CMO"],
    business_area: "Technology, Media and Telecoms",
    funnel_stage: "Proof",
    key_claims: [
      "TMT is both a producer and early adopter of AI solutions.",
      "AI is embedded in TMT business activity rather than peripheral experimentation.",
      "TMT faces the fastest pace of skills transformation across sectors.",
    ],
    proof_points: [
      "In 2025, AI roles accounted for 11.9% of total job postings in TMT.",
      "TMT AI roles grew by 82.7% in 2025, outpacing overall job growth.",
      "AI-enabled employees in TMT earned an 84% wage premium relative to non-AI roles in 2025.",
      "TMT recorded 42% productivity growth from 2018 to 2025, the highest across sectors in the report.",
    ],
    suggested_use:
      "Use as the pilot TMT sector cut for clients already building, scaling or commercialising AI.",
    suggested_sales_enablement_use:
      "Help TMT partners open with scarcity, skills velocity and the need for distinctive judgement.",
    related_asset_ids: ["pwc-ai-jobs-global", "pwc-ai-performance"],
    ai_confidence_score: 0.94,
    metadata_status: "Human approved",
    content_usefulness: "Sector cut",
    url_status: "Accessible",
    message_role: "Sector cut",
    message_spine_alignment: 4,
    core_truth_supported: true,
    provocation_supported: true,
    claims_to_avoid: commonClaimsToAvoid,
    sector_cuts: ["TMT"],
    role_cuts: ["CEO", "CIO / CTO", "CHRO", "CMO"],
    moments_that_matter: ["I am exploring opportunities", "I need you to deliver outcomes"],
    partner_prompt_types: ["LinkedIn post starter", "Comment starter", "Short video prompt"],
    cultural_availability_score: 5,
    partner_readiness_score: 5,
    proof_strength_score: 5,
    moment_readiness_score: 4,
    activation_quality_total: 24,
    activation_labels: ["Sector cut", "Strong proof point", "Conversation starter"],
    recommended_partner_use:
      "Use when TMT leaders need a sharper point on why AI skill scarcity and human expertise now shape growth.",
    why_it_matters:
      "It shows a market where AI is already central, making distinct expert judgement more valuable rather than less.",
  },
  {
    id: "pwc-responsible-ai",
    title: "AI designed for you: responsible AI methodology",
    url: "https://www.pwc.com/gx/en/services/ai.html",
    canonical_url: "https://www.pwc.com/gx/en/services/ai.html",
    source_type: "PwC services page section",
    platform: "pwc.com",
    format: "Service page section",
    language: "English",
    region: "Global",
    published_date: null,
    last_seen_date: "2026-06-19",
    last_crawled_date: "2026-06-19",
    raw_text:
      "PwC describes responsible AI as security, ethics, compliance, controls and governance across the value chain, with AI solutions that adapt to future requirements.",
    summary:
      "A trust and guardrails source for partner-ready AI claims, especially when clients ask about responsibility and compliance.",
    primary_topic: "Responsible AI",
    secondary_topics: ["AI assurance and trust", "Risk and governance", "Data and trust"],
    audience: ["CRO / Risk leader", "CIO / CTO", "CEO"],
    business_area: "Trust and risk",
    funnel_stage: "Consideration",
    key_claims: [
      "Fast-moving technology requires rigorous security, ethics and compliance.",
      "Responsible AI needs controls and governance at every step.",
      "AI solutions should meet immediate needs while adapting to future requirements.",
    ],
    proof_points: [
      "PwC lists responsible AI principles, controls and governance across the value chain as part of its methodology.",
      "PwC's AI consultancy includes regulatory compliance across global and local contexts.",
      "PwC positions AI-readiness assessments and real-world simulations as part of market planning.",
    ],
    suggested_use:
      "Use as a guardrail source when partners need to avoid hype and show responsible adoption discipline.",
    suggested_sales_enablement_use:
      "Equip CRO, risk and CIO conversations on controls, governance and compliance by design.",
    related_asset_ids: ["pwc-ai-services", "pwc-ai-performance"],
    ai_confidence_score: 0.91,
    metadata_status: "Human edited",
    content_usefulness: "Partner prompt source",
    url_status: "Accessible",
    message_role: "Partner prompt",
    message_spine_alignment: 4,
    core_truth_supported: true,
    provocation_supported: false,
    claims_to_avoid: commonClaimsToAvoid,
    sector_cuts: ["Financial Services", "TMT", "Global markets"],
    role_cuts: ["CRO / Risk leader", "CIO / CTO", "CEO"],
    moments_that_matter: ["I want PwC's help", "I need you to deliver outcomes"],
    partner_prompt_types: ["Q&A prep", "Claims to avoid", "Sales talking point"],
    cultural_availability_score: 4,
    partner_readiness_score: 4,
    proof_strength_score: 4,
    moment_readiness_score: 5,
    activation_quality_total: 21,
    activation_labels: ["Partner prompt source", "Sales follow-up", "Conversation starter"],
    recommended_partner_use:
      "Use when a partner needs to make the Human Scale message credible, practical and properly bounded.",
    why_it_matters:
      "It protects the voice layer by making claims specific, responsible and rooted in PwC's approved methodology.",
  },
  {
    id: "pwc-human-skills",
    title: "Human-intensive skills in the AI era",
    url: "https://www.pwc.com/gx/en/services/ai/ai-jobs-barometer.html",
    canonical_url: "https://www.pwc.com/gx/en/services/ai/ai-jobs-barometer.html",
    source_type: "PwC research report section",
    platform: "pwc.com",
    format: "Insight section",
    language: "English",
    region: "Global",
    published_date: "2026-06-16",
    last_seen_date: "2026-06-19",
    last_crawled_date: "2026-06-19",
    raw_text:
      "PwC recommends investing in human-intensive skills such as empathy, judgement, creativity and leadership alongside AI skills.",
    summary:
      "A role-cut source for partners who need to make Human Scale AI personal, not abstract.",
    primary_topic: "Workforce and AI",
    secondary_topics: ["Human Scale AI", "AI transformation"],
    audience: ["CHRO", "CEO", "CMO"],
    business_area: "Workforce",
    funnel_stage: "Education",
    key_claims: [
      "AI changes the human expertise required for job roles.",
      "Early career pathways need redesign as AI changes entry-level work.",
      "Human-intensive skills become more important as AI handles more routine work.",
    ],
    proof_points: [
      "PwC recommends investing in human-intensive skills alongside AI skills: empathy, judgement, creativity and leadership.",
      "Skills needed for the most AI-exposed jobs are changing more than twice as fast as for the least AI-exposed jobs.",
      "AI-exposed junior roles are seven times more likely to demand traditionally senior skills like leadership.",
    ],
    suggested_use:
      "Use as a partner voice bridge for explaining why Human Scale AI depends on judgement and interpretation.",
    suggested_sales_enablement_use:
      "Equip CHRO and CMO conversations on voice, skills and expert participation.",
    related_asset_ids: ["pwc-ai-jobs-global", "pwc-ai-services"],
    ai_confidence_score: 0.9,
    metadata_status: "Human edited",
    content_usefulness: "Role cut",
    url_status: "Accessible",
    message_role: "Role cut",
    message_spine_alignment: 5,
    core_truth_supported: true,
    provocation_supported: true,
    claims_to_avoid: commonClaimsToAvoid,
    sector_cuts: ["Financial Services", "TMT", "UK market", "Global markets"],
    role_cuts: ["CHRO", "CEO", "CMO"],
    moments_that_matter: ["I am setting my strategy", "I am exploring opportunities"],
    partner_prompt_types: ["LinkedIn post starter", "Short video prompt", "Event follow-up note"],
    cultural_availability_score: 5,
    partner_readiness_score: 5,
    proof_strength_score: 4,
    moment_readiness_score: 4,
    activation_quality_total: 23,
    activation_labels: ["Partner prompt source", "Conversation starter", "Role cut"],
    recommended_partner_use:
      "Use when a partner wants to sound distinctly human while staying inside the approved evidence base.",
    why_it_matters:
      "It gives the Human Scale idea its emotional and practical center: people still create the meaning clients use.",
  },
];

export const topicClusters = [
  {
    id: "human-scale-ai",
    name: "Human Scale AI",
    topics: ["Human Scale AI", "AI transformation", "Workforce and AI"],
    signal: "Strong spine, proof-rich, ready for partner interpretation.",
  },
  {
    id: "trust-governance",
    name: "Trust, Assurance and Governance",
    topics: ["Responsible AI", "AI assurance and trust", "Risk and governance", "Data and trust"],
    signal: "Strong guardrails, needs more role-native stories for CFO and CRO.",
  },
  {
    id: "sector-cuts",
    name: "FS and TMT Sector Cuts",
    topics: ["Financial Services AI", "TMT AI"],
    signal: "Pilot-ready proof for FS and TMT; UK-specific examples should come next.",
  },
  {
    id: "infrastructure-platforms",
    name: "AI Infrastructure and Platforms",
    topics: ["AI infrastructure and platforms", "Digital transformation"],
    signal: "Good operating-model proof, thinner on partner-ready examples.",
  },
];

export const initialSources = [
  {
    id: "source-pwc-ai-services",
    type: "PwC services page",
    label: "PwC artificial intelligence services",
    url: "https://www.pwc.com/gx/en/services/ai.html",
    cadence: "Monthly review",
    owner: "Global AI marketing",
    last_checked: "2026-06-19",
    status: "Approved source",
    notes: "Use for proposition, responsible AI methodology and service language.",
  },
  {
    id: "source-pwc-ai-jobs",
    type: "PwC research report",
    label: "Global AI Jobs Barometer",
    url: "https://www.pwc.com/gx/en/services/ai/ai-jobs-barometer.html",
    cadence: "Campaign cycle",
    owner: "Workforce and AI thought leadership",
    last_checked: "2026-06-19",
    status: "Approved source",
    notes: "Use for proof around human skills, productivity, wages and role redesign.",
  },
  {
    id: "source-pwc-ceo-survey",
    type: "PwC flagship survey",
    label: "Global CEO Survey",
    url: "https://www.pwc.com/gx/en/issues/c-suite-insights/ceo-survey.html",
    cadence: "Annual refresh",
    owner: "C-suite insights",
    last_checked: "2026-06-19",
    status: "Approved source",
    notes: "Use for executive agenda, uncertainty, reinvention and AI value context.",
  },
  {
    id: "source-pwc-ai-performance",
    type: "PwC performance study",
    label: "Decoding ROI from AI",
    url: "https://www.pwc.com/gx/en/issues/technology/ai-performance.html",
    cadence: "Quarterly review",
    owner: "Technology thought leadership",
    last_checked: "2026-06-19",
    status: "Approved source",
    notes: "Use for AI value, operating discipline, foundations and scale proof.",
  },
  {
    id: "source-pwc-fs-sector",
    type: "PwC sector PDF",
    label: "Financial Services AI Jobs Barometer sector report",
    url: "https://www.pwc.com/gx/en/issues/artificial-intelligence/job-barometer/2026/pwc-aijb-2026-financial-services-report.pdf",
    cadence: "Pilot refresh",
    owner: "Financial Services marketing",
    last_checked: "2026-06-19",
    status: "Approved source",
    notes: "Use as FS pilot sector cut. Convert PDF proof into partner-ready prompts.",
  },
  {
    id: "source-pwc-tmt-sector",
    type: "PwC sector PDF",
    label: "TMT AI Jobs Barometer sector report",
    url: "https://www.pwc.com/gx/en/issues/artificial-intelligence/job-barometer/2026/pwc-aijb-2026-technology-media-and-telecoms-report.pdf",
    cadence: "Pilot refresh",
    owner: "TMT marketing",
    last_checked: "2026-06-19",
    status: "Approved source",
    notes: "Use as TMT pilot sector cut. Convert sector proof into partner voice prompts.",
  },
];

export const measurementSignals = [
  {
    label: "Recognised thinking",
    status: "Ready field",
    description: "Track language clients recognise and repeat in meetings.",
  },
  {
    label: "Repeated language in market",
    status: "Ready field",
    description: "Monitor approved phrases that show up in briefs, comments and event questions.",
  },
  {
    label: "Saves and forwards",
    status: "Ready field",
    description: "Capture useful sharing signals without treating them as final performance proof.",
  },
  {
    label: "Comments and challenges",
    status: "Ready field",
    description: "Tag the questions and objections that show an idea is travelling.",
  },
  {
    label: "Peer and partner mentions",
    status: "Ready field",
    description: "Record approved partner use and internal expert reuse.",
  },
  {
    label: "Sales feedback",
    status: "Ready field",
    description: "Connect proof points to client questions and conversation outcomes.",
  },
  {
    label: "Search visibility",
    status: "Future signal",
    description: "Prepare for search and AI answer references without inventing current performance.",
  },
  {
    label: "Sector reuse",
    status: "Ready field",
    description: "Track where global proof is adapted into FS, TMT and market cuts.",
  },
];
